# Generated by Django 4.2.30 on 2026-05-21 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Jordan', 'Jordan'), ('New Balance', 'New Balance'), ('Puma', 'Puma'), ('Vans', 'Vans'), ('Converse', 'Converse'), ('Asics', 'Asics'), ('Reebok', 'Reebok'), ('Otra', 'Otra')], max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('talla', models.CharField(max_length=10)),
                ('precio', models.PositiveIntegerField()),
                ('condicion', models.CharField(choices=[('new', 'Nueva'), ('used', 'Usada'), ('rare', 'Edición limitada')], default='used', max_length=10)),
                ('despacho', models.CharField(choices=[('yes', 'Todo Chile'), ('local', 'Solo presencial'), ('both', 'Envío y presencial')], default='yes', max_length=10)),
                ('ciudad', models.CharField(default='Santiago', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('vendida', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(default='Santiago', max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('verificado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='listings/%Y/%m/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['orden', 'creado'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_escritas', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.sellerprofile')),
            ],
            options={
                'ordering': ['-creado'],
                'unique_together': {('vendedor', 'autor', 'listing')},
            },
        ),
    ]
