# Generated by Django 4.2.30 on 2026-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='caja_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='categoria',
            field=models.CharField(choices=[('zapatillas', 'Zapatillas'), ('streetwear', 'Streetwear'), ('accesorios', 'Accesorios Sneaker'), ('coleccion', 'Colección')], default='zapatillas', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='colorway',
            field=models.CharField(blank=True, help_text='ej: Black/White, Bred, University Blue', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='precio_original',
            field=models.PositiveIntegerField(blank=True, help_text='Precio de retail original', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('basketball', 'Basketball'), ('lifestyle', 'Lifestyle'), ('skate', 'Skate'), ('training', 'Training / Gym'), ('boots', 'Boots'), ('polera', 'Polera / T-Shirt'), ('hoodie', 'Hoodie / Poleron'), ('pants', 'Pants / Joggers'), ('chaqueta', 'Chaqueta / Jacket'), ('gorro', 'Gorro / Cap'), ('calcetines', 'Calcetines'), ('cordones', 'Cordones / Laces'), ('cleaning', 'Cleaning Kit'), ('insoles', 'Plantillas / Insoles'), ('shields', 'Crease Protectors / Shields'), ('cajas', 'Cajas / Display'), ('bolso', 'Bolso / Cartera'), ('lentes', 'Lentes'), ('figura', 'Figura / Funko'), ('poster', 'Poster / Art Print'), ('libro', 'Libro / Revista'), ('otro_col', 'Otro coleccionable')], default='lifestyle', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condicion',
            field=models.CharField(choices=[('ds', 'DS — Deadstock (sin usar, caja original)'), ('vnds', 'VNDS — Very Near Deadstock (1-2 usos)'), ('used', 'Used — Usada (buen estado)'), ('beater', 'Beater — Muy usada')], default='used', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='marca',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Jordan', 'Jordan'), ('Adidas', 'Adidas'), ('New Balance', 'New Balance'), ('Asics', 'Asics'), ('Puma', 'Puma'), ('Vans', 'Vans'), ('Converse', 'Converse'), ('Reebok', 'Reebok'), ('Saucony', 'Saucony'), ('On Running', 'On Running'), ('Salehe', 'Salehe'), ('Yeezy', 'Yeezy'), ('Off-White', 'Off-White'), ('Travis Scott', 'Travis Scott'), ('Supreme', 'Supreme'), ('Palace', 'Palace'), ('Stüssy', 'Stüssy'), ('BAPE', 'BAPE'), ('Carhartt', 'Carhartt WIP'), ('Dickies', 'Dickies'), ('Anti Social', 'Anti Social Social Club'), ('Kith', 'Kith'), ('Crep Protect', 'Crep Protect'), ('Jason Markk', 'Jason Markk'), ('Reshoevn8r', 'Reshoevn8r'), ('Huf', 'HUF'), ('Stance', 'Stance'), ('Otra', 'Otra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='talla',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
